### ISSUE TITLE
Implement streaming for the /v1/chat/completions route

### ISSUE THREAD

**Issue by ianpurton** [AmineDiro/cria#19]
I think `/v1/completions` has streaming code but not `/v1/chat/completions` the former API is deprecated and I'm using the new one.

To me it also looks like the code could be combined somehow? i.e. after creating the prompt from the incoming JSON with reference to https://github.com/AmineDiro/cria/issues/18

Perhaps it's a case of passing it to the streaming code in `routes/completions.rs`

So you're are aware and for some context to my requests we have integrated `cria` into https://github.com/purton-tech/bionicgpt

Thanks

**Comment by AmineDiro** [comment]
Oh wow ! thanks for using this project and hope I can help !
Yes, I rewrote the routing to use a single inferer process (as a blocking tokio task) and use async communication via queues when receiving requests. The previous implementation was spawning an inference session for each requests, the session was created from a clone to a `State(Arc<dyn Model>` which was possible because Model Sync but the Session is not. 
This caused GPU memory issues when receiving multiple requests.

Having Chat streaming responses is not that difficult, you can see the pattern in the `completion` route
https://github.com/AmineDiro/cria/blob/50ba66cf0a69fb3836f38ad79e48ddff817ced78/src/routes/completions.rs#L18  

Also, all the scaffolding is actually done for having a streaming chat ; 
https://github.com/AmineDiro/cria/blob/50ba66cf0a69fb3836f38ad79e48ddff817ced78/src/inferer.rs#L151

I didn't find the time to implement the streaming version yet. I'll take a look at this this weekend.
